### 포인트 적립 취소 테스트
DELETE http://localhost:8080/free-point/earn
Content-Type: application/json

{
  "pointSrl" : 7
}

### 이미 취소된 적립 건 다시 취소해보기
DELETE http://localhost:8080/free-point/earn
Content-Type: application/json

{
  "pointSrl" : 7
}

### 일부 사용 건 취소해보기
DELETE http://localhost:8080/free-point/earn
Content-Type: application/json

{
  "pointSrl" : 2
}